# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
