# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_speciality_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='deleted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='etks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
