# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171119_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.TextField()),
                ('salary', models.CharField(blank=True, max_length=60, null=True)),
                ('regionId', models.CharField(max_length=30)),
                ('relocation', models.BooleanField()),
            ],
        ),
    ]
